<a href="https://colab.research.google.com/github/rajayadavm17/python/blob/main/advpython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=[]
print(a)
type(a)
id(a)
#dir(a)

[]


137608161761408

In [ ]:
a=[10,20,30]
print(a)

[10, 20, 30]


In [ ]:
import numpy as np
x=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(x)
print(x[0,0])
print(x[0,1])
print(x[0,2])
print(x[1,0])
print(x[1,1])
print(x[1,2])
print(x[2,0])
print(x[2,1])
print(x[2,2])


[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
20
30
40
50
60
70
80
90


In [ ]:
import numpy as np
raja=np.zeros(5)
print(raja)
print(type(raja))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
raja=np.ones(5)
print(raja)
print(type(raja))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
raja=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(raja)
print(raja.shape)
print(type(raja))
print(raja.ndim)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
<class 'numpy.ndarray'>
2


In [ ]:
import numpy as np
raja=np.array([10,20,30])
print(raja)
print(raja.shape)
print(type(raja))
print(raja.ndim)

[10 20 30]
(3,)
<class 'numpy.ndarray'>
1


In [ ]:
import numpy as np
raja=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(raja)
print(raja.shape)
print(type(raja))
print(raja.ndim)
print(raja.T)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
<class 'numpy.ndarray'>
2
[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [ ]:
import numpy as np
raja=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(raja)
print(raja.min())
print(raja.max())
print(raja.reshape(1,9))
print(raja.reshape(9,1))
print(raja.sum())
print(raja.flatten())

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
90
[[10 20 30 40 50 60 70 80 90]]
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]
450
[10 20 30 40 50 60 70 80 90]


# ***PANDAS***

In [ ]:
import pandas as pd
d1 = {
"Id": [1, 2, 3, 4, 5, 6],
"Name": ["Pradhan", "Venu", "Madhurima", "Nireekshan",
"Shafi", "Veeru"],
"Subject": ["English", "Java", "Html", "Python", "C", "dotnet"]
}
d2 = {
"Id": [11, 12, 13, 14, 15, 16],
"Name": ["Srinu", "Sumanth", "Neelima", "Daniel", "Arjun",
"Veeru"],
"Subject": ["Java", "Html", "Cpp", "Python", "C", "dot net"]
}
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)
print(df1)
print()
print(df2)
print()
print(type(d1))

   Id        Name  Subject
0   1     Pradhan  English
1   2        Venu     Java
2   3   Madhurima     Html
3   4  Nireekshan   Python
4   5       Shafi        C
5   6       Veeru   dotnet

   Id     Name  Subject
0  11    Srinu     Java
1  12  Sumanth     Html
2  13  Neelima      Cpp
3  14   Daniel   Python
4  15    Arjun        C
5  16    Veeru  dot net

<class 'dict'>


In [ ]:
import pandas as pd
d1 = {
"Id": [1, 2, 3, 4, 5, 6],
"Name": ["Pradhan", "Venu", "Madhurima", "Nireekshan",
"Shafi", "Veeru"],
"Subject": ["English", "Java", "Html", "Python", "C", "dotnet"]
}
d2 = {
"Id": [11, 12, 13, 14, 15, 16],
"Name": ["Srinu", "Sumanth", "Neelima", "Daniel", "Arjun",
"Veeru"],
"Subject": ["Java", "Html", "Cpp", "Python", "C", "dot net"]
}
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)
inn_join = pd.merge(df1, df2, on = "Subject", how = "inner")
print(df1)
print()
print(df2)
print()
print(inn_join)

   Id        Name  Subject
0   1     Pradhan  English
1   2        Venu     Java
2   3   Madhurima     Html
3   4  Nireekshan   Python
4   5       Shafi        C
5   6       Veeru   dotnet

   Id     Name  Subject
0  11    Srinu     Java
1  12  Sumanth     Html
2  13  Neelima      Cpp
3  14   Daniel   Python
4  15    Arjun        C
5  16    Veeru  dot net

   Id_x      Name_x Subject  Id_y   Name_y
0     2        Venu    Java    11    Srinu
1     3   Madhurima    Html    12  Sumanth
2     4  Nireekshan  Python    14   Daniel
3     5       Shafi       C    15    Arjun


In [ ]:
import pandas as pd
d1 = {
"Id": [1, 2, 3, 4, 5, 6],
"Name": ["Pradhan", "Venu", "Madhurima", "Nireekshan",
"Shafi", "Veeru"],
"Subject": ["English", "Java", "Html", "Python", "C", "dotnet"]
}
d2 = {
"Id": [11, 12, 13, 14, 15, 16],
"Name": ["Srinu", "Sumanth", "Neelima", "Daniel", "Arjun",
"Veeru"],
"Subject": ["Java", "Html", "Cpp", "Python", "C", "dot net"]
}
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)
left_join = pd.merge(df1, df2, on = "Subject", how = "left")
print(df1)
print()
print(df2)
print()
print(left_join)

   Id        Name  Subject
0   1     Pradhan  English
1   2        Venu     Java
2   3   Madhurima     Html
3   4  Nireekshan   Python
4   5       Shafi        C
5   6       Veeru   dotnet

   Id     Name  Subject
0  11    Srinu     Java
1  12  Sumanth     Html
2  13  Neelima      Cpp
3  14   Daniel   Python
4  15    Arjun        C
5  16    Veeru  dot net

   Id_x      Name_x  Subject  Id_y   Name_y
0     1     Pradhan  English   NaN      NaN
1     2        Venu     Java  11.0    Srinu
2     3   Madhurima     Html  12.0  Sumanth
3     4  Nireekshan   Python  14.0   Daniel
4     5       Shafi        C  15.0    Arjun
5     6       Veeru   dotnet   NaN      NaN


In [ ]:
import pandas as pd

d1 = {
"Id": [1, 2, 3, 4, 5, 6],
"Name": ["Pradhan", "Venu", "Madhurima", "Nireekshan",
"Shafi", "Veeru"],
"Subject": ["English", "Java", "Html", "Python", "C", "dotnet"]
}

d2 = {
"Id": [11, 12, 13, 14, 15, 16],
"Name": ["Srinu", "Sumanth", "Neelima", "Daniel", "Arjun",
"Veeru"],
"Subject": ["Java", "Html", "Cpp", "Python", "C", "dotnet"]
}

df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

right_join = pd.merge(df1, df2, on = "Subject", how = "right")

print(df1)
print()
print(df2)
print()
print(right_join)

   Id        Name  Subject
0   1     Pradhan  English
1   2        Venu     Java
2   3   Madhurima     Html
3   4  Nireekshan   Python
4   5       Shafi        C
5   6       Veeru   dotnet

   Id     Name Subject
0  11    Srinu    Java
1  12  Sumanth    Html
2  13  Neelima     Cpp
3  14   Daniel  Python
4  15    Arjun       C
5  16    Veeru  dotnet

   Id_x      Name_x Subject  Id_y   Name_y
0   2.0        Venu    Java    11    Srinu
1   3.0   Madhurima    Html    12  Sumanth
2   NaN         NaN     Cpp    13  Neelima
3   4.0  Nireekshan  Python    14   Daniel
4   5.0       Shafi       C    15    Arjun
5   6.0       Veeru  dotnet    16    Veeru
